### ISSUE TITLE
Search Results Component

### ISSUE THREAD

**Issue by dashcraft** [data-umbrella/event-board-web#143]
We're focusing on style issues, no features will be added in this ticket. The pagination and limiting of search results, map views, etc will be implemented in a separate ticket.

[Figma Link](https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=1457%3A6573)
[Figma Link](https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=1457%3A4452)

- [x] Color change to #E7E1F6 on view option buttons
- [x] Color change to #6B26FF on view buttons when selected

- [x] Change mouse over over view buttons to pointer instead of i-beam
- [x] Make "Search Results" and view option buttons visible across view options
- [x] Color change for list view buttons on dark mode to #EEEAF8
- [x] Color change for selected list view button on dark mode to #9747FF
- [x] Color change for text to #F7FAFC in dark mode
- [x] Color change event borders (#00FFFF) appropriately for dark mode
- [x] Dark mode background needs to cover pages and change dark mode color to #151A35 (fixed by ticket PR #235)
- [x] Remove view options for mobile
- [ ] Color code event types for calendar, list view, mobile

- [x] Change mobile search results date format to month, date range, year
- [x] Change mobile search results list view order to date then color-coded clickable event title
