### ISSUE TITLE
Search Results Grid and List View

### ISSUE THREAD

**Issue by dashcraft** [data-umbrella/event-board-web#145]
Focus on visual changes, if there's missing features disregard and reticket.

[Figma Link](https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=1457%3A4635)

## Grid View

- [x] Increase top padding between grid results and "Search Results"/View opts
- [ ] Resize grid items- increase width decrease height (check figma to double check)
- [ ] Text color change to #783D86 for date and cost for grid events
- [ ] Change date format to month, day, year for grid events
- [ ] Text color change to #C86DFF for date and cost for grid events in dark mode
- [ ] Text color change to #F7FAFC for event name for grid events in dark mode
- [ ] Decrease l/r padding between grid events

## List View

- [ ] Add event type label ( if being returned from backend, otherwise disregard )
- [ ] Color change hyperlinks to #6B26FF for list events
- [ ] Color change to #4B4B4B for event list dates
- [ ] Add color coding to event types in list view dark mode
- [ ] Color change hyperlinks to #C86DFF for list events in dark mode
- [ ] Color change text for event list dates to #F7FAFC in dark mode
