### ISSUE TITLE
(Tasks to be split into separate issues) Missing Features from event show Page

### ISSUE THREAD

**Issue by dashcraft** [data-umbrella/event-board-web#150]
These are missing features from the event show page, if api collects this information we might add it, if not, we can move it to a further iteration.

## JS
- [ ] Link to update personal calendar with event details (generate an ical link) (Issue #323 )
- [ ] Time Zone Converter = unfinished component  + missing (Issue #365)
- [ ] Add share buttons for Twitter Facebook and Linkedin (Issue #117 or new issue)
- [ ] Event information = unfinished component + missing content (description, speakers, volunteering notes, notes, accessiblity options) (Completed)
