### ISSUE TITLE
Create Twitter account for automated tweets

### ISSUE THREAD

**Issue by jtorreggiani** [data-umbrella/event-board-web#41]
**Tasks**

- [x] Create Twitter account for Event Board (https://twitter.com/DataEventsBoard)
- [ ] Generate API token from Twitter admin console
- [ ] Add API token as environment variable in Digital Ocean (coordinate with eng)

**Note**

This task unblocks [this ticket](https://github.com/data-umbrella/event-board-api/issues/39)

**Comment by reshamas** [comment]
@jtorreggiani 
I have the Twitter account for the event board:
https://twitter.com/data_events_

**Comment by reshamas** [comment]
@jtorreggiani I wonder if I should rename this to "data__events" since that "_" at the end in Markdown is not read, so leads to:
- "data_events" instead of "data_events_"
https://twitter.com/data_events_

**Comment by YolineB** [comment]
Confirm for next development cycle

**Comment by reshamas** [comment]
Deactivated the Twitter account:
https://twitter.com/DataEventsBoard
